name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Install dependencies
      run: npm install --no-package-lock

    - name: Run tests
      run: npm test
      continue-on-error: true
